#!/bin/bash
# AI Rescue Linux - Build Configuration
# Run this before building to embed your API keys and preferences

set -e

CONFIG_DIR="config/includes.chroot/etc/ai-rescue"
CONFIG_FILE="$CONFIG_DIR/credentials.env"
PROFILE_HOOK="config/includes.chroot/etc/profile.d/ai-rescue-credentials.sh"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         AI Rescue Linux - Build Configuration               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This will embed your API keys into the ISO so AI tools work"
echo "immediately on boot without manual configuration."
echo ""
echo "Leave blank to skip any option. Keys are stored in the ISO."
echo ""
echo "WARNING: Anyone with access to the ISO can extract these keys."
echo "         Only use for personal rescue USBs, not public distribution."
echo ""
read -rp "Continue? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Configuration cancelled."
    exit 0
fi

# Create config directory
mkdir -p "$CONFIG_DIR"
mkdir -p "$(dirname "$PROFILE_HOOK")"

# Start fresh config
cat > "$CONFIG_FILE" << 'HEADER'
# AI Rescue Linux - Embedded Credentials
# Generated by configure.sh
# These are loaded automatically on boot
HEADER

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "                      AI Provider API Keys"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Anthropic (Claude)
echo "1. Anthropic (Claude Code) - RECOMMENDED"
echo "   Get key at: https://console.anthropic.com/"
read -rp "   ANTHROPIC_API_KEY: " ANTHROPIC_KEY
if [ -n "$ANTHROPIC_KEY" ]; then
    echo "export ANTHROPIC_API_KEY='$ANTHROPIC_KEY'" >> "$CONFIG_FILE"
    echo "   ✓ Saved"
else
    echo "   ○ Skipped"
fi

echo ""

# OpenAI
echo "2. OpenAI (GPT-4, Codex)"
echo "   Get key at: https://platform.openai.com/api-keys"
read -rp "   OPENAI_API_KEY: " OPENAI_KEY
if [ -n "$OPENAI_KEY" ]; then
    echo "export OPENAI_API_KEY='$OPENAI_KEY'" >> "$CONFIG_FILE"
    echo "   ✓ Saved"
else
    echo "   ○ Skipped"
fi

echo ""

# Google (Gemini)
echo "3. Google (Gemini)"
echo "   Get key at: https://aistudio.google.com/apikey"
read -rp "   GOOGLE_API_KEY: " GOOGLE_KEY
if [ -n "$GOOGLE_KEY" ]; then
    echo "export GOOGLE_API_KEY='$GOOGLE_KEY'" >> "$CONFIG_FILE"
    echo "export GEMINI_API_KEY='$GOOGLE_KEY'" >> "$CONFIG_FILE"
    echo "   ✓ Saved"
else
    echo "   ○ Skipped"
fi

echo ""

# GitHub (Copilot)
echo "4. GitHub Token (for Copilot CLI)"
echo "   Get token at: https://github.com/settings/tokens"
read -rp "   GITHUB_TOKEN: " GITHUB_TOKEN
if [ -n "$GITHUB_TOKEN" ]; then
    echo "export GITHUB_TOKEN='$GITHUB_TOKEN'" >> "$CONFIG_FILE"
    echo "   ✓ Saved"
else
    echo "   ○ Skipped"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "                      User Preferences"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Custom username
echo "5. Custom username (default: rescue)"
read -rp "   Username: " CUSTOM_USER
if [ -n "$CUSTOM_USER" ]; then
    echo "$CUSTOM_USER" > "$CONFIG_DIR/custom-username"
    echo "   ✓ Will create user: $CUSTOM_USER"
else
    echo "   ○ Using default: rescue"
fi

echo ""

# Custom password
echo "6. Custom password (default: rescue)"
read -rs -p "   Password: " CUSTOM_PASS
echo ""
if [ -n "$CUSTOM_PASS" ]; then
    echo "$CUSTOM_PASS" > "$CONFIG_DIR/custom-password"
    echo "   ✓ Custom password set"
else
    echo "   ○ Using default: rescue"
fi

echo ""

# Timezone
echo "7. Timezone (default: UTC)"
echo "   Examples: America/New_York, Europe/London, Asia/Tokyo"
read -rp "   Timezone: " CUSTOM_TZ
if [ -n "$CUSTOM_TZ" ]; then
    echo "$CUSTOM_TZ" > "$CONFIG_DIR/custom-timezone"
    echo "   ✓ Timezone: $CUSTOM_TZ"
else
    echo "   ○ Using default: UTC"
fi

echo ""

# Keyboard layout
echo "8. Keyboard layout (default: us)"
echo "   Examples: us, uk, de, fr, es"
read -rp "   Layout: " CUSTOM_KB
if [ -n "$CUSTOM_KB" ]; then
    echo "$CUSTOM_KB" > "$CONFIG_DIR/custom-keyboard"
    echo "   ✓ Keyboard: $CUSTOM_KB"
else
    echo "   ○ Using default: us"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "                      Optional: Local AI"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "9. Pre-download Ollama model for offline use?"
echo "   This will increase ISO size but enable offline AI."
echo "   Models: llama2 (~4GB), mistral (~4GB), phi (~1.5GB)"
read -rp "   Model name (or blank to skip): " OLLAMA_MODEL
if [ -n "$OLLAMA_MODEL" ]; then
    echo "$OLLAMA_MODEL" > "$CONFIG_DIR/ollama-model"
    echo "   ✓ Will include: $OLLAMA_MODEL (adds ~4GB to ISO)"
else
    echo "   ○ Skipped (Ollama available but no pre-loaded model)"
fi

# Create profile.d script to load credentials on login
cat > "$PROFILE_HOOK" << 'PROFILE'
#!/bin/bash
# Load AI Rescue Linux credentials
if [ -f /etc/ai-rescue/credentials.env ]; then
    source /etc/ai-rescue/credentials.env
fi
PROFILE
chmod +x "$PROFILE_HOOK"

# Secure the credentials file
chmod 600 "$CONFIG_FILE"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "                      Configuration Complete"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Configuration saved to: $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. Run: sudo ./build.sh"
echo "  2. Write ISO to USB"
echo "  3. Boot and enjoy pre-configured AI tools!"
echo ""
echo "To reconfigure, run: ./configure.sh"
echo "To build without config, delete: $CONFIG_DIR"
echo ""
